prepare:
		echo "make prepare successfully!"
start:
		echo "make start successfully!"
restart:
		echo "make restart successfully!"
stop:
		echo "make stop successfully!"
status:
		echo "make status successfully!"
status_dns:
		echo "make status_dns successfully!"
status_sskcp:
		echo "make status_sskcp successfully!"
status_bypass:
		echo "make status_bypass successfully!"
restart_dns:
		echo "make restart_dns successfully!"
restart_sskcp:
		echo "make restart_sskcp successfully!"
restart_bypass:
		echo "make restart_bypass successfully!"
remove:
		echo "make remove successfully!"
install:
		echo "make install successfully!"
uninstall:
		echo "make uninstall sucessfully!"
gen_config:
		echo "make gen_conf successfully!"

set_config:
		echo "make set_conf successfully!"

restore_config:
		echo "make restore_conf successfully!"

rm_config:
		echo "make rm_conf successfully!"

get_state:
		echo "make get_state successfully!"

pop_config:
		echo "make pop_config successfully!"

showconf:
		echo "make showconf successfully!"

showinfo:
		echo "make showinfo successfully!"

show_queued_info:
		echo "make show_queued_info successfully!"

show_queued_conf:
		echo "make show_queued_conf successfully!"

test_state:
		echo "make test_state successfully!"

update:
		echo "make update successfully!"
















