language: generic

sudo: false
dist: trusty

branches:
  only:
    - /^\d+(\.\d+){2}$/

env:
  global:
    - PROJECT="powter-server"
    - VERSION="$TRAVIS_TAG"

install: true

script:
  - make build version=${VERSION}
  - make build-testflow version=${VERSION}

deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    secure: meLK7R201bRDrMed1IxjL4zJlBIVPqmpXLRuMTwrZHalI0/ks/+XUhEy/FLjSg038q5aSPrKhfkrcuYKBSGhmXcJtF8b8IamJDpX4B3dQG26JEtFrAVP/aKn3ps1hnjq3BU6b3AK4rL0ZkGLKv2WDKwm5jp0U9K5N1gBprgwdE1FE0+hcElogr99bmyRTwpgPRYUs1xPXKKQUYMM+spm64ylXetTg8y+Shjq1TxKpCb6ATn2oGZq+uDgFUDSpYQkUwbkyhj+a+kxINkG5REVk/HeOFC8iLXGjDB3thDA3ym4/A3uUQjphw/LAWVdoEJczb8CT7zX9jVUmjd5v78ChjDi+7knTLQ/Wc6LePjbE/M+rQqkKemTn8YSpW5o0vL2C+sbErIHNG34JFwIgxlKAcz3yg0hOdNvjfoNFpykQLRL1HKMHpAsen+Z8WGRsWlxuqdEZavA6qM83EcsjIMmK/fEA5+UnlHhI/06zG6eCY9N2B3AknwTDM8nNKik//j5dgsadrEVqXXzbpNavc7JjRk5cW25RtUhs1BTjIzmxDbBLv0eEcVM7Fnmjew99nrBM1rT4R92iTQOgZAk33JAG3oso36J8USRHaJY8svLGSnq/oMc3Jp0Uepq6v3IdtlV7xVmYAJzAloZFflPt7p1vbejXDffciry2hsJTx9OMm4=
  file: 
    - "${PROJECT}-${VERSION}.zip"
    - "${PROJECT}-testflow-${VERSION}.zip"
  on:
    tags: true
    all_branches: true
    repo: hilanderas/powter-server
